services:
  mongodb:
    image: 'mongo:latest'
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongo-keyfile"]
    environment:
      - 'MONGO_INITDB_DATABASE=aplly'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-keyfile:/data/mongo-keyfile:ro
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 -u root -p secret --authenticationDatabase admin --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s