import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NavBar } from "@/app/_components/ui/NavBar";
import { Toaster } from "sonner";

// Configuração das fontes Geist
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased", 
        geistSans.variable, 
        geistMono.variable
      )}
    >
      { /*
        Definimos 'font-sans' no body para que a Geist Sans seja a fonte padrão do projeto.
        Se precisar usar a Geist Mono em algum lugar, basta usar a classe 'font-mono'.
      */}
      <body className="min-h-full flex flex-col font-sans">
        {children}
        <Toaster/>
      </body>        
    </html>
  );
}
