spring.application.name=backend
spring.application.version=0.0.1
jwt.secret=;f>A&WHOuu##meultgPWOIFs*7?#mpR5s$y/#(;UvN%GU;tfePL5:k6MyEP
jwt.expiration-ms=36000000
spring.mongodb.uri=${MONGODB_URI:mongodb://root:secret@localhost:27017/aplly?authSource=admin}
spring.mongodb.database=aplly
springdoc.swagger-ui.enabled=true
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none